

CREATE TABLE `primer_login` (
  `ACTIVIDAD_ID` bigint NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint DEFAULT NULL,
  `SESSION_ID` bigint DEFAULT NULL,
  `SEGMENT_ID` bigint DEFAULT NULL,
  `SEGMENT_DESCRIPTION` text,
  `USER_CITY_ID` bigint DEFAULT NULL,
  `EVENT_ID` bigint DEFAULT NULL,
  `SERVER_TIME_ID` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `TIME_SPENT` bigint DEFAULT NULL,
  `DEVICE_BROWSER` text,
  `DEVICE_MOBILE` text,
  `DEVICE_OS` text,
  
  PRIMARY KEY (`ACTIVIDAD_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=117 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `tiempo` (
  `FECHA_ID` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dia` bigint DEFAULT NULL,
  `mes` bigint DEFAULT NULL,
  `anio` bigint DEFAULT NULL,
  `hora` bigint DEFAULT NULL,
  `minuto` bigint DEFAULT NULL,
  `segundo` bigint DEFAULT NULL,
  PRIMARY KEY (`FECHA_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `actividad_session` (
  `ACTIVIDAD_ID` bigint NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint DEFAULT NULL,
  `SESSION_ID` bigint DEFAULT NULL,
  `SEGMENT_ID` bigint DEFAULT NULL,
  `SEGMENT_DESCRIPTION` text,
  `USER_CITY_ID` bigint DEFAULT NULL,
  `EVENT_ID` bigint DEFAULT NULL,
  `SERVER_TIME_ID` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `TIME_SPENT` bigint DEFAULT NULL,
  `DEVICE_BROWSER` text,
  `DEVICE_MOBILE` text,
  `DEVICE_OS` text,
  `DOSD_FL` int DEFAULT NULL,
  `EVENT_DESCRIPTION` varchar(45) NOT NULL,
  `CHRASH_DETECTION` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ACTIVIDAD_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=143 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ciudad` (
  `USER_CITY_ID` int NOT NULL,
  `NOMBRE` varchar(45) NOT NULL,
  PRIMARY KEY (`USER_CITY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;



